"  ██▒   █▓ ██▓ ███▄ ▄███▓ ██▀███   ▄████▄
" ▓██░   █▒▓██▒▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█
"  ▓██  █▒░▒██▒▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄
"   ▒██ █░░░██░▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒
"    ▒▀█░  ░██░▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░
"    ░ ▐░  ░▓  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░
"    ░ ░░   ▒ ░░  ░      ░  ░▒ ░ ▒░  ░  ▒
"      ░░   ▒ ░░      ░     ░░   ░ ░
"       ░   ░         ░      ░     ░ ░
"      ░                           ░
"
" install vimplug somehow before runing vim

" syntax, indent, filetype
syntax on
filetype plugin indent on

" plugins
call plug#begin()
    Plug 'hossein-lap/vim-lupper'
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'jesseleite/vim-noh'
    Plug 'tpope/vim-commentary'
call plug#end()

" settings
set ignorecase
set smartcase
set incsearch
set smartcase
set smartindent
set smarttab
set expandtab
set cindent
set tabstop=2
set shiftwidth=2
set encoding=UTF-8
set ttimeoutlen=50
set wildoptions-=pum
set signcolumn=yes
au GUIEnter * simalt ~x

" use system clipboard with just space
nnoremap <space> "+
vnoremap <space> "+

" change leader key
let mapleader=","

" mark trailing spaces as errors
match Error '\s\+$'


" custom autochdir (default not working when switching directories in netrw
" and also when i type :e /home/user - it sets current directory to /home,
" when i want it to be /home/user (like in dired mode in emacs))
" sollution from here:
" https://vi.stackexchange.com/questions/34557/how-can-i-use-let-gnetrw-keepdir-0-for-folders-and-autochdir-for-files
" https://gist.github.com/user202729/483421a9e88af58def12f2e085dc1c02
set noautochdir  " otherwise it conflict with netrw. Implement manually
let g:netrw_keepdir=0  " i.e. pwd = current browsing directory
function NetrwCheckAcd()
	" could also be "terminal" or something in which case do nothing
	if &buftype==""
		if isdirectory(expand("%"))
			call chdir(expand("%"))  " this is still necessary even with g:netrw_keepdir when triggered through remote vim...? TODO
		else
			if isdirectory(expand("%:h"))
				call chdir(expand("%:h"))  " simulate acd. Do this even in case % does not exist
			endif
		endif
	endif
endfunction
autocmd BufEnter * call NetrwCheckAcd()


" git grep instead of default grep
set grepprg=git\ grep\ -rni


" netrw no banner
let g:netrw_banner=0

" colorscheme
colorscheme lupper

" ctrlp
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
nnoremap <C-b> :CtrlPBuffer<cr>

" gui
set guifont=Courier\ New:h14
set guioptions=Ace
set guicursor=a:block-Cursor-blinkwait0-blinkoff0-blinkon0
set titlestring=Отче\ наш,\ Иже\ еси\ на\ небесе́х
