# settings_____________________________________________________________________

# `tmux attach` with no sessions starts new session
new-session -n $HOST

# without it escape in vim working after one second
set -sg escape-time 10


# keybinds_____________________________________________________________________

# kill pane
bind -n M-q kill-pane

# horizontal split
unbind l
unbind C-l
bind-key l split-window -h
bind-key C-l split-window -h

# veritcal split
unbind j
unbind C-j
bind-key j split-window
bind-key C-j split-window

# switch pane
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# switch window
bind -n M-o next-window
bind -n M-i previous-window

bind -n M-1 select-window -t 0
bind -n M-2 select-window -t 1
bind -n M-3 select-window -t 2
bind -n M-4 select-window -t 3
bind -n M-5 select-window -t 4
bind -n M-6 select-window -t 5
bind -n M-7 select-window -t 6
bind -n M-8 select-window -t 7
bind -n M-9 select-window -t 8

# new window
bind -n M-n new-window
