#!/bin/bash

# dir contains this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# remove all from user dir
rm -rf $DIR/user/

#create dirs
mkdir -p $DIR/user/.config

# copy files
cp -r ~/.bg $DIR/user/
cp -r ~/.config/nvim $DIR/user/.config/
cp -r ~/.config/alacritty $DIR/user/.config/
cp -r ~/.config/bspwm $DIR/user/.config/
cp -r ~/.config/picom $DIR/user/.config/
cp -r ~/.config/sxhkd $DIR/user/.config/
cp -r ~/.config/polybar $DIR/user/.config/
cp -r ~/.config/tmux $DIR/user/.config/
cp -r ~/.config/htop $DIR/user/.config/
cp -r ~/.config/pipewire $DIR/user/.config/
cp -r ~/.config/zathura $DIR/user/.config/
cp -r ~/.config/dunst $DIR/user/.config/
cp "~/.config/Code - OSS/User/keybindings.json" $DIR/user/
cp "~/.config/Code - OSS/User/settings.json" $DIR/user/
cp ~/.xinitrc $DIR/user/
cp ~/.bashrc $DIR/user/
cp ~/.gitconfig $DIR/user/

# remove trash
rm -rf $DIR/user/.config/nvim/vimspector/gadgets

# open lazy git to view changes
lazygit
