#!/bin/bash

# dir contains this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# remove all from user dir
rm -rf $DIR/user/

#create dirs
mkdir $DIR/user
mkdir $DIR/user/.config
mkdir $DIR/user/.bg
mkdir $DIR/user/.cabal

# copy files
cp -r ~/.bg $DIR/user/
cp -r ~/.config/nvim $DIR/user/.config/
cp -r ~/.config/sway $DIR/user/.config/
cp -r ~/.config/alacritty $DIR/user/.config/
cp -r ~/.config/tmux $DIR/user/.config/
cp -r ~/.config/htop $DIR/user/.config/
cp -r ~/.config/pipewire $DIR/user/.config/
cp ~/.bashrc $DIR/user/
cp ~/.ghci $DIR/user/
cp ~/.gitconfig $DIR/user/
cp ~/.cabal/config $DIR/user/.cabal/config

# remove trash
rm -rf $DIR/user/.config/nvim/vimspector/gadgets
rm -rf $DIR/user/.config/nvim/plugin
