#!/bin/bash

# dir contains this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# remove all from user dir
rm -rf $DIR/user/

#create dirs
mkdir $DIR/user
mkdir $DIR/user/.config
mkdir $DIR/user/.scripts
mkdir $DIR/user/.bg

# copy configs
cp -r ~/.config/nvim $DIR/user/.config/
cp -r ~/.config/bspwm $DIR/user/.config/
cp -r ~/.config/sxhkd $DIR/user/.config/
cp -r ~/.config/picom $DIR/user/.config/
cp -r ~/.config/polybar $DIR/user/.config/
cp ~/.xinitrc $DIR/user/
cp -r ~/.config/alacritty $DIR/user/.config/
cp -r ~/.config/tmux $DIR/user/.config/
cp ~/.bashrc $DIR/user/
cp ~/.gitconfig $DIR/user/

# remove trash
rm -rf $DIR/user/.config/nvim/vimspector/gadgets
rm -rf $DIR/user/.config/nvim/plugin

# copy scripts
cp -r ~/.scripts $DIR/user/

# copy backgrounds
cp -r ~/.bg $DIR/user/
