#!/bin/bash

# variables
ls /sys/firmware/efi/efivars && BOOT=efi || BOOT=bios

fdisk -l | less
echo "disk to install arch (all data will be deleted) '/dev/sdx':"
read DISK
export DISK

echo "username:"
read USERNAME
export USERNAME

echo "hostname:"
read HOSTNAME
export HOSTNAME


# partition the disks
if [ "$BOOT" == "bios" ]; then
    printf "g\nn\n\n\n+1M\nt\n4\nn\n\n\n\nw\n" | fdisk "$DISK"
else
    printf "g\nn\n\n\n+512M\nt\n1\nn\n\n\n\nw\n" | fdisk "$DISK"
    mkfs.fat -F 32 "$DISK"1
fi
mkfs.ext4 "$DISK"2

# mount
mount "$DISK"2 /mnt
if [ "$BOOT" == "efi" ]; then
    mkdir -p /mnt/boot
    mount "$DISK"1 /mnt/boot
fi

# install base
pacstrap /mnt base base-devel linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
mkdir -p /mnt/arch_setup
cp -r "$DIR"/* /mnt/arch_setup/
# chroot
arch-chroot /mnt "/arch_setup/install_after_chroot"
