#!/bin/bash

# dir contains this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# install paru
"$DIR"/scripts/paru_install

# update software
paru -Syu

# install all another software with paru
for NAME in $(cat "$DIR"/install_lists/paru)
do
    paru -S --noconfirm "$NAME"
done

# copy config files
cp -r "$DIR"/user/. ~

# enable services
"$DIR"/scripts/services

# configuring bash on system start
ln -s ~/.bashrc ~/.profile

# install python libs
for NAME in $(cat "$DIR"/install_lists/pip)
do
    pip install "$NAME"
done

# ask user to reboot
echo "please reboot now"
