# disable trash
enable_audio_bell no

# font
font_family      DejaVu Sans Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

# cursor
cursor_shape block
cursor_blink_interval 0
shell_integration  no-cursor

# padding
window_padding_width 4

# opacity
background_opacity 0.8

# colors
background            #000000
foreground            #CDCDCD
cursor                #f2f2f2

selection_background  #545454
color0                #000000
color8                #545454
color1                #cc6666
color9                #cc6666
color2                #a1bf78
color10               #a1bf78
color3                #E5C078
color11               #E5C078
color4                #7D8FA3
color12               #7D8FA3
color5                #9F7AA5
color13               #9F7AA5
color6                #888888
color14               #888888
color7                #f2f2f2
color15               #f2f2f2
selection_foreground #8fafd7
