set-window-option -g mode-keys vi

set -sg escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g history-limit 120015
set-option -g status-style fg=default,bg=default
set-option -g status-right ""
set-option -g status-left ""

unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key x kill-pane
bind-key -T copy-mode-vi y send -X copy-pipe-no-clear "xclip -sel clipboard" \; send-keys -X cancel
bind-key ] run "tmux set-buffer \"$(xclip -o -sel clipboard)\" && tmux paste-buffer"
