#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9

# autostart
pkill sxhkd

sxhkd &
feh --bg-center ~/.bg/bg1.png &
pgrep -x picom > /dev/null || picom &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x Discord > /dev/null || discord  &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -x firefox > /dev/null || firefox  &
~/.config/polybar/launch.sh &


# borders
bspc config focused_border_color "#373737"
bspc config normal_border_color "#000000"
bspc config border_width 1
bspc config window_gap 0
bspc config single_monocle 	true
bspc config borderless_monocle true
bspc config gapless_monocle true


# split
bspc config split_ratio 0.5


# window rules
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a discord desktop='^9'
bspc rule -a flameshot state=floating
