#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9

# autostart
pkill sxhkd

sxhkd &
feh --bg-fill ~/.bg/bg3.png &
pgrep -x picom > /dev/null || picom &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x Discord > /dev/null || discord &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -wf firefox > /dev/null || firefox &
~/.scripts/polybar &


# borders
bspc config focused_border_color "#373737"
bspc config normal_border_color "#000000"
bspc config border_width 1
bspc config window_gap 0
bspc config single_monocle 	true
bspc config borderless_monocle true
bspc config gapless_monocle true


# split
bspc config split_ratio 0.5


# window rules

bspc rule -a 'firefox:Toolkit' state=floating sticky=true
bspc rule -a Alacritty state=floating sticky=true
bspc rule -a code-oss desktop='^3'
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a discord desktop='^9'
bspc rule -a flameshot state=floating
bspc rule -a feh state=floating
